In [1]:
from PIL import ImageFile
import keras as K
import cv2
import os

Using TensorFlow backend.


In [10]:
class CameraAngleClassifier():
    def __init__(self, trackViewModelFilename, otherViewModelFilename):
        super().__init__()
        self.isTrackViewModel = K.models.load_model(trackViewModelFilename)
        self.otherViewModel = K.models.load_model(otherViewModelFilename)

    def getCameraAngle(self, x):
        isTrackView = self.isTrackViewModel.predict(x, steps=1)
        print(isTrackView)


In [12]:
cameraAngleClassifier = CameraAngleClassifier("IsTrackViewModel.h5", "OtherViewModel.h5")

In [21]:
filedir = '../../data/test/isOtherView'
count = 0
for filename in os.listdir(filedir):
    image = cv2.imread(os.path.join(filedir, filename), cv2.IMREAD_COLOR)
    image = K.backend.reshape(K.backend.constant(cv2.resize(image, (299, 299))), shape=(1, 299, 299, 3))
    cameraAngleClassifier.getCameraAngle(image)
    count += 1
    if count > 100:
        break

[[0. 1.]]
[[0. 1.]]
[[1.04145934e-22 1.00000000e+00]]
[[0. 1.]]
[[9.1937245e-30 1.0000000e+00]]
[[0. 1.]]


In [19]:
for layer in cameraAngleClassifier.isTrackViewModel.layers:
    print("{} => {}".format(layer.input_shape, layer.output_shape))
print('=========================================')
for layer in cameraAngleClassifier.otherViewModel.layers:
    print("{} => {}".format(layer.input_shape, layer.output_shape))

(None, 299, 299, 3) => (None, 2048)
(None, 2048) => (None, 2)
(None, 299, 299, 3) => (None, 2048)
(None, 2048) => (None, 4)
